image: node:12.18.3

stages:
  - tests

cache:
  paths:
    - node_modules/

tests:
  stage: tests
  script:
    - npm install
    - npm run test:db
    - npm run test:server
  artifacts:
    when: always
    reports:
        junit: artifacts/junit-*.xml
