version: '3'
services:
  app:
    container_name: reviews-service
    restart: always
    image: tandyn/rpt23-reviews-service
    ports:
      - '3001:3001'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - '27017:27017'
  proxy:
    container_name: proxy
    restart: always
    image: tandyn/rpt23-proxy-server
    ports:
      - '80:80'
