version: '3'
services:
  app:
    container_name: reviews-service
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - '27017:27017'
